name: flutter_shopper
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6

  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1

  flutter_overlay_loader: ^1.0.3

  flutter_riverpod: ^2.0.0-dev.5
  flutter_form_bloc: ^0.30.1
  

  font_awesome_flutter: ^10.1.0
  flutter_native_splash: ^2.2.4

  freezed_annotation: ^2.0.3
  flutter_svg: ^1.0.1

  get_it: ^7.2.0
  google_fonts: 2.2.0

  hooks_riverpod: ^2.0.0-dev.5

  image_fade: ^0.6.1

  json_annotation: ^4.5.0
  nb_utils: ^4.4.12

  percent_indicator: ^4.2.2
  phosphor_flutter: ^1.4.0
  transparent_image: ^2.0.0
  simple_gradient_text: ^1.2.2
  splash_screen_view: ^2.0.1

  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.1
  url_launcher: ^6.0.20

  modal_bottom_sheet: ^2.1.0
  freezed: ^2.0.5
  flutter_cache_manager: ^3.3.0

dependency_overrides:
  analyzer: ^4.1.0
  #analyzer: ^3.0.0
dev_dependencies:
  auto_route_generator: ^4.0.0

  build_runner: any
  flutter_gen_runner: ^4.1.5
  change_app_package_name: ^1.1.0
  #retrofit_generator: ^4.0.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_native_splash:
  image: assets/images/splash.png
  color: "#01221D"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
#
